apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - args:
        - go
        - run
        - main.go
        env:
        - name: PGPASSWORD
          value: N+JmM7za4^zvq4ezK-dcc*dbszRWQ*9fDc
        - name: PGUSER
          value: postgres
        image: treydecker75/redeamapi:golang
        name: api
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /go/src/github.com/redeamapi
          name: api-claim0
        workingDir: /go/src/github.com/redeamapi
      restartPolicy: Always
      volumes:
      - name: api-claim0
        persistentVolumeClaim:
          claimName: api-claim0
status: {}
