version: '2'
services:
  db:
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=redeamapi
      - POSTGRES_PASSWORD=N+JmM7za4^zvq4ezK-dcc*dbszRWQ*9fDc$W9Ud
      - PGDATA/pgdata
  
  api:
    build:
      context: ./
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./api:/go/src/github.com/redeamapi
    ports:
      - "9000:9000"
    links:
      - db
