version: '3'
services:
  db:
    image: postgres
    volumes: 
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_DB=book_store
  api:
    image: golang
    expose:
      - 9000
    ports:
      - 9000:9000
    volumes:
      - .:/go/src/github.com/redeamapi
    working_dir: /go/src/github.com/redeamapi
    environment:
      - PGUSER=postgres
      - PGPASSWORD=N+JmM7za4^zvq4ezK-dcc*dbszRWQ*9fDc$W9Ud
    command: go run main.go
    depends_on:
      - db
    links:
      - db:db

volumes:
  db-data:
    driver: local